"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mapKeys = mapKeys;
/**
 * Creates an object with the same values as `object` and keys generated by running each own enumerable string keyed property of `object` through `iteratee`.
 * The iteratee is invoked with three arguments: (value, key, object).
 *
 * @param object - The object to iterate over
 * @param iteratee - The function invoked per iteration
 * @returns Returns the new mapped object
 *
 * @example
 * ```typescript
 * mapKeys({ 'a': 1, 'b': 2 }, (value, key) => key + value);
 * // => { 'a1': 1, 'b2': 2 }
 * ```
 */
function mapKeys(object, iteratee) {
    if (!object || typeof object !== 'object') {
        return {};
    }
    const result = {};
    for (const key in object) {
        if (Object.prototype.hasOwnProperty.call(object, key)) {
            const value = object[key];
            const newKey = typeof iteratee === 'function'
                ? iteratee(value, key, object)
                : String(value[iteratee]);
            result[newKey] = value;
        }
    }
    return result;
}
